name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Version and Release
    runs-on: ubuntu-latest
    concurrency: release

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Generate App Token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.SEMVER_APP_ID }}
          private-key: ${{ secrets.SEMVER_APP_KEY }}

      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@v10.5.3
        with:
          github_token: ${{ steps.app-token.outputs.token }}
